# @baseUrl = http://localhost:4300
@baseUrl = https://45.32.39.52:4001

###
# @name getClasss
GET {{baseUrl}}/students

###
# @name getStudents
GET {{baseUrl}}/students?q=ANn&classId=1


###
# @name createClass
POST {{baseUrl}}/students
Content-Type: application/json

{
      "fullName": "C 444",
      "englishName": "C 123",
      "dob": "2011-01-01",
      "phoneNumber": "",
      "email": "",
      "prinberkAccounts": "",
      "studentEmailGCH": "",
      "classId": 999,
      "point": 0,
      "winStreak": 0,
      "streakNumber": 0,
      "notes": ""
    }

###
PATCH  {{baseUrl}}/students/1
Content-Type: application/json

{
   "point": 0,
    "winStreak": 0,
    "streakNumber": 0
    
}
